# PySNMP SMI module. Autogenerated from smidump -f python JUNIPER-FRU-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:57:50 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( jnxFruMibRoot, jnxFruTraps, ) = mibBuilder.importSymbols("JUNIPER-SMI", "jnxFruMibRoot", "jnxFruTraps")
( Bits, Integer32, Integer32, ModuleIdentity, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class JnxFruAdminStates(Integer):
    subtypeSpec = Integer.subtypeSpec+SingleValueConstraint(2,1,)
    namedValues = NamedValues(("inService", 1), ("outOfService", 2), )
    
class JnxFruOperStates(Integer):
    subtypeSpec = Integer.subtypeSpec+SingleValueConstraint(1,2,4,5,3,6,)
    namedValues = NamedValues(("unEquipped", 1), ("init", 2), ("normal", 3), ("mismatched", 4), ("fault", 5), ("swul", 6), )
    

# Objects

jnxFruMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1)).setRevisions(("2012-11-13 14:14","2012-01-26 00:00",))
if mibBuilder.loadTexts: jnxFruMib.setOrganization("Juniper Networks, Inc.")
if mibBuilder.loadTexts: jnxFruMib.setContactInfo("        Juniper Technical Assistance Center\nJuniper Networks, Inc.\n1194 N. Mathilda Avenue\nSunnyvale, CA 94089\nE-mail: support@juniper.net")
if mibBuilder.loadTexts: jnxFruMib.setDescription("This MIB module defines objects used for managing the\nOTN FRU's for Juniper products.")
jnxFruCfg = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1))
jnxFruCfgTable = MibTable((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1))
if mibBuilder.loadTexts: jnxFruCfgTable.setDescription("Information about the otn FRU's. ")
jnxFruCfgEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1)).setIndexNames((0, "JUNIPER-FRU-MIB", "jnxFruCfgContentsIndex"), (0, "JUNIPER-FRU-MIB", "jnxFruCfgL1Index"), (0, "JUNIPER-FRU-MIB", "jnxFruCfgL2Index"), (0, "JUNIPER-FRU-MIB", "jnxFruCfgL3Index"))
if mibBuilder.loadTexts: jnxFruCfgEntry.setDescription("Information about the otn FRU's.")
jnxFruCfgContentsIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 2147483647))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxFruCfgContentsIndex.setDescription("The associated jnxContentsContainerIndex in the \njnxContentsTable.")
jnxFruCfgL1Index = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 2), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxFruCfgL1Index.setDescription("The level one index associated with this\nsubject.  Zero if unavailable or inapplicable.")
jnxFruCfgL2Index = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxFruCfgL2Index.setDescription("The level two index associated with this \nsubject.  Zero if unavailable or inapplicable.")
jnxFruCfgL3Index = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxFruCfgL3Index.setDescription("The level three index associated with this\nsubject.  Zero if unavailable or inapplicable.")
jnxFruCfgType = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 5), ObjectIdentifier()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: jnxFruCfgType.setDescription("The object ID for this FRU")
jnxFruCfgAdminState = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 6), JnxFruAdminStates()).setMaxAccess("readwrite")
if mibBuilder.loadTexts: jnxFruCfgAdminState.setDescription("The Administrative state of this FRU")
jnxFruCfgOperState = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 74, 1, 1, 1, 1, 7), JnxFruOperStates()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxFruCfgOperState.setDescription("The Operational state of this FRU")

# Augmentions

# Notifications

jnxFruNotifMismatch = NotificationType((1, 3, 6, 1, 4, 1, 2636, 4, 23, 1)).setObjects(*(("JUNIPER-FRU-MIB", "jnxFruCfgL1Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL2Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL3Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgType"), ("JUNIPER-FRU-MIB", "jnxFruCfgContentsIndex"), ) )
if mibBuilder.loadTexts: jnxFruNotifMismatch.setDescription("A jnxFruInsertion trap signifies that the SNMP\nentity, acting in an agent role, has detected that\nthe specified FRU (Field Replaceable Unit)  \ninserted into the chassis does not match what was\nconfigured.")
jnxFruNotifAdminStatus = NotificationType((1, 3, 6, 1, 4, 1, 2636, 4, 23, 2)).setObjects(*(("JUNIPER-FRU-MIB", "jnxFruCfgL1Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL2Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL3Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgAdminState"), ("JUNIPER-FRU-MIB", "jnxFruCfgContentsIndex"), ) )
if mibBuilder.loadTexts: jnxFruNotifAdminStatus.setDescription("Notification of the Administrative state of the otn interface")
jnxFruNotifOperStatus = NotificationType((1, 3, 6, 1, 4, 1, 2636, 4, 23, 3)).setObjects(*(("JUNIPER-FRU-MIB", "jnxFruCfgL1Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL2Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgL3Index"), ("JUNIPER-FRU-MIB", "jnxFruCfgOperState"), ("JUNIPER-FRU-MIB", "jnxFruCfgContentsIndex"), ) )
if mibBuilder.loadTexts: jnxFruNotifOperStatus.setDescription("Notification of Operational state of the otn interface")

# Exports

# Module identity
mibBuilder.exportSymbols("JUNIPER-FRU-MIB", PYSNMP_MODULE_ID=jnxFruMib)

# Types
mibBuilder.exportSymbols("JUNIPER-FRU-MIB", JnxFruAdminStates=JnxFruAdminStates, JnxFruOperStates=JnxFruOperStates)

# Objects
mibBuilder.exportSymbols("JUNIPER-FRU-MIB", jnxFruMib=jnxFruMib, jnxFruCfg=jnxFruCfg, jnxFruCfgTable=jnxFruCfgTable, jnxFruCfgEntry=jnxFruCfgEntry, jnxFruCfgContentsIndex=jnxFruCfgContentsIndex, jnxFruCfgL1Index=jnxFruCfgL1Index, jnxFruCfgL2Index=jnxFruCfgL2Index, jnxFruCfgL3Index=jnxFruCfgL3Index, jnxFruCfgType=jnxFruCfgType, jnxFruCfgAdminState=jnxFruCfgAdminState, jnxFruCfgOperState=jnxFruCfgOperState)

# Notifications
mibBuilder.exportSymbols("JUNIPER-FRU-MIB", jnxFruNotifMismatch=jnxFruNotifMismatch, jnxFruNotifAdminStatus=jnxFruNotifAdminStatus, jnxFruNotifOperStatus=jnxFruNotifOperStatus)

