# PySNMP SMI module. Autogenerated from smidump -f python NETSCREEN-IPPOOL-MIB
# by libsmi2pysnmp-0.1.3 at Fri May 30 14:12:55 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( netscreenVpn, netscreenVpnMibModule, ) = mibBuilder.importSymbols("NETSCREEN-SMI", "netscreenVpn", "netscreenVpnMibModule")
( Bits, Integer32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks")
( DisplayString, ) = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString")

# Objects

netscreenIppoolMibModule = ModuleIdentity((1, 3, 6, 1, 4, 1, 3224, 4, 0, 9)).setRevisions(("2004-05-03 20:22","2004-05-03 00:00","2004-03-03 00:00","2003-11-13 00:00","2001-09-28 00:00","2000-08-27 00:00",))
if mibBuilder.loadTexts: netscreenIppoolMibModule.setOrganization("Juniper Networks, Inc.")
if mibBuilder.loadTexts: netscreenIppoolMibModule.setContactInfo("Customer Support\n\n1194 North Mathilda Avenue \nSunnyvale, California 94089-1206\nUSA\n\nTel: 1-800-638-8296\nE-mail: customerservice@juniper.net\nHTTP://www.juniper.net")
if mibBuilder.loadTexts: netscreenIppoolMibModule.setDescription("This module defines the object that are used to monitor \nVPN IP pool")
nsVpnIpPool = MibIdentifier((1, 3, 6, 1, 4, 1, 3224, 4, 9))
nsVpnIpPoolTable = MibTable((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1))
if mibBuilder.loadTexts: nsVpnIpPoolTable.setDescription("This table collects all ip pool configuration in NetScreen\ndevice.")
nsVpnIpPoolEntry = MibTableRow((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1)).setIndexNames((0, "NETSCREEN-IPPOOL-MIB", "nsVpnIpPoolIndex"))
if mibBuilder.loadTexts: nsVpnIpPoolEntry.setDescription("Each entry in the nsVpnIpPoolEntry holds a set of\nconfiguration parameters associated with an instance IP pool.")
nsVpnIpPoolIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 2147483647))).setMaxAccess("readonly")
if mibBuilder.loadTexts: nsVpnIpPoolIndex.setDescription("A unique value for ip pool.  Its value ranges between 0 and\n65535 and may not be contiguous.")
nsVpnIpPoolName = MibTableColumn((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1, 2), DisplayString().subtype(subtypeSpec=ValueSizeConstraint(0, 32))).setMaxAccess("readonly")
if mibBuilder.loadTexts: nsVpnIpPoolName.setDescription("ip pool name")
nsVpnIpPoolStartIp = MibTableColumn((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1, 3), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: nsVpnIpPoolStartIp.setDescription("IP pool's start ip address.")
nsVpnIpPoolEndIp = MibTableColumn((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1, 4), IpAddress()).setMaxAccess("readonly")
if mibBuilder.loadTexts: nsVpnIpPoolEndIp.setDescription("IP pool's end ip address.")
nsVpnIpPoolIpUsed = MibTableColumn((1, 3, 6, 1, 4, 1, 3224, 4, 9, 1, 1, 5), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: nsVpnIpPoolIpUsed.setDescription("Total number of addresses in use from this pool.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("NETSCREEN-IPPOOL-MIB", PYSNMP_MODULE_ID=netscreenIppoolMibModule)

# Objects
mibBuilder.exportSymbols("NETSCREEN-IPPOOL-MIB", netscreenIppoolMibModule=netscreenIppoolMibModule, nsVpnIpPool=nsVpnIpPool, nsVpnIpPoolTable=nsVpnIpPoolTable, nsVpnIpPoolEntry=nsVpnIpPoolEntry, nsVpnIpPoolIndex=nsVpnIpPoolIndex, nsVpnIpPoolName=nsVpnIpPoolName, nsVpnIpPoolStartIp=nsVpnIpPoolStartIp, nsVpnIpPoolEndIp=nsVpnIpPoolEndIp, nsVpnIpPoolIpUsed=nsVpnIpPoolIpUsed)

