# PySNMP SMI module. Autogenerated from smidump -f python OLD-CISCO-TCP-MIB
# by libsmi2pysnmp-0.1.3 at Tue May 27 10:13:42 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( local, ) = mibBuilder.importSymbols("CISCO-SMI", "local")
( MibScalar, MibTable, MibTableRow, MibTableColumn, ) = mibBuilder.importSymbols("RFC-1212", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn")
( TimeTicks, ) = mibBuilder.importSymbols("RFC1155-SMI", "TimeTicks")
( tcpConnLocalAddress, tcpConnLocalPort, tcpConnRemAddress, tcpConnRemPort, ) = mibBuilder.importSymbols("RFC1213-MIB", "tcpConnLocalAddress", "tcpConnLocalPort", "tcpConnRemAddress", "tcpConnRemPort")
( Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")

# Objects

ltcp = MibIdentifier((1, 3, 6, 1, 4, 1, 9, 2, 6))
ltcpConnTable = MibTable((1, 3, 6, 1, 4, 1, 9, 2, 6, 1))
if mibBuilder.loadTexts: ltcpConnTable.setDescription("A list of TCP connection entries.")
ltcpConnEntry = MibTableRow((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1)).setIndexNames((0, "RFC1213-MIB", "tcpConnLocalAddress"), (0, "RFC1213-MIB", "tcpConnLocalPort"), (0, "RFC1213-MIB", "tcpConnRemAddress"), (0, "RFC1213-MIB", "tcpConnRemPort"))
if mibBuilder.loadTexts: ltcpConnEntry.setDescription("A collection of additional objects in the\ncisco TCP implementation.")
loctcpConnInBytes = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: loctcpConnInBytes.setDescription("Bytes input for this TCP connection.")
loctcpConnOutBytes = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: loctcpConnOutBytes.setDescription("Bytes output for this TCP connection.")
loctcpConnInPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1, 3), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: loctcpConnInPkts.setDescription("Packets input for this TCP connection.")
loctcpConnOutPkts = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1, 4), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: loctcpConnOutPkts.setDescription("Packets output for this TCP connection.")
loctcpConnElapsed = MibTableColumn((1, 3, 6, 1, 4, 1, 9, 2, 6, 1, 1, 5), TimeTicks()).setMaxAccess("readonly")
if mibBuilder.loadTexts: loctcpConnElapsed.setDescription("How long this TCP connection has been\nestablished.")

# Augmentions

# Exports

# Objects
mibBuilder.exportSymbols("OLD-CISCO-TCP-MIB", ltcp=ltcp, ltcpConnTable=ltcpConnTable, ltcpConnEntry=ltcpConnEntry, loctcpConnInBytes=loctcpConnInBytes, loctcpConnOutBytes=loctcpConnOutBytes, loctcpConnInPkts=loctcpConnInPkts, loctcpConnOutPkts=loctcpConnOutPkts, loctcpConnElapsed=loctcpConnElapsed)

