# PySNMP SMI module. Autogenerated from smidump -f python ITU-ALARM-TC-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:57:45 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "mib-2")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class ItuPerceivedSeverity(Integer):
    subtypeSpec = Integer.subtypeSpec+SingleValueConstraint(4,3,6,1,2,5,)
    namedValues = NamedValues(("cleared", 1), ("indeterminate", 2), ("critical", 3), ("major", 4), ("minor", 5), ("warning", 6), )
    
class ItuTrendIndication(Integer):
    subtypeSpec = Integer.subtypeSpec+SingleValueConstraint(1,2,3,)
    namedValues = NamedValues(("moreSevere", 1), ("noChange", 2), ("lessSevere", 3), )
    

# Objects

ituAlarmTc = ModuleIdentity((1, 3, 6, 1, 2, 1, 120)).setRevisions(("2004-09-09 00:00",))
if mibBuilder.loadTexts: ituAlarmTc.setOrganization("IETF Distributed Management Working Group")
if mibBuilder.loadTexts: ituAlarmTc.setContactInfo(" WG EMail: disman@ietf.org\nSubscribe: disman-request@ietf.org\nhttp://www.ietf.org/html.charters/disman-charter.html\n\nChair:     Randy Presuhn\n           randy_presuhn@mindspring.com\n\nEditors:   Sharon Chisholm\n           Nortel Networks\n           PO Box 3511 Station C\n           Ottawa, Ont.  K1Y 4H7\n           Canada\n           schishol@nortelnetworks.com\n\n           Dan Romascanu\n           Avaya\n           Atidim Technology Park, Bldg. #3\n           Tel Aviv, 61131\n           Israel\n           Tel: +972-3-645-8414\n           Email: dromasca@avaya.com")
if mibBuilder.loadTexts: ituAlarmTc.setDescription("This MIB module defines the ITU Alarm\ntextual convention for objects not expected to require\nregular extension.\n\nCopyright (C) The Internet Society (2004).  The\ninitial version of this MIB module was published\nin RFC 3877.  For full legal notices see the RFC\nitself.  Supplementary information may be available on:\nhttp://www.ietf.org/copyrights/ianamib.html")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("ITU-ALARM-TC-MIB", PYSNMP_MODULE_ID=ituAlarmTc)

# Types
mibBuilder.exportSymbols("ITU-ALARM-TC-MIB", ItuPerceivedSeverity=ItuPerceivedSeverity, ItuTrendIndication=ItuTrendIndication)

# Objects
mibBuilder.exportSymbols("ITU-ALARM-TC-MIB", ituAlarmTc=ituAlarmTc)

