# PySNMP SMI module. Autogenerated from smidump -f python JUNIPER-BFD-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:57:48 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( bfdSessIndex, ) = mibBuilder.importSymbols("BFD-STD-MIB", "bfdSessIndex")
( jnxBfdMibRoot, ) = mibBuilder.importSymbols("JUNIPER-SMI", "jnxBfdMibRoot")
( Bits, Integer32, ModuleIdentity, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32")
( DisplayString, TimeStamp, TruthValue, ) = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TimeStamp", "TruthValue")

# Objects

jnxBfdMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1)).setRevisions(("2006-10-12 12:00",))
if mibBuilder.loadTexts: jnxBfdMib.setOrganization("IETF")
if mibBuilder.loadTexts: jnxBfdMib.setContactInfo("        Juniper Technical Assistance Center\nJuniper Networks, Inc.\n1194 N. Mathilda Avenue\nSunnyvale, CA 94089\nE-mail: support@juniper.net")
if mibBuilder.loadTexts: jnxBfdMib.setDescription("Provides BFD specific data.")
jnxBfdNotification = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 0))
jnxBfdObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1))
jnxBfdSessTable = MibTable((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1))
if mibBuilder.loadTexts: jnxBfdSessTable.setDescription("Defines the jnxBfd Session Table for providing enterprise \nspecific options to the corresponding bfdSessTable entry.")
jnxBfdSessEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1)).setIndexNames((0, "BFD-STD-MIB", "bfdSessIndex"))
if mibBuilder.loadTexts: jnxBfdSessEntry.setDescription("Defines an entry in the jnxBfdSessTable.  This essentially\naugments the bfdSessTable with additional objects.")
jnxBfdSessThreshTxInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxBfdSessThreshTxInterval.setDescription("The threshold value for transmit interval in microseconds.  \nIf the current transmit interval value adapts to a value \ngreater than the  threshold value, jnxBfdSessTxIntervalHigh \ntrap is raised.")
jnxBfdSessCurrTxInterval = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxBfdSessCurrTxInterval.setDescription("The current transmit interval in microseconds.")
jnxBfdSessThreshDectTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxBfdSessThreshDectTime.setDescription("The threshold value for detection time in microseconds.  \nIf the current detection time value is greater than the  \nthreshold value at the time when session state changes \nto up(1), jnxBfdSessDetectionTimeHigh trap is raised.")
jnxBfdSessCurrDectTime = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxBfdSessCurrDectTime.setDescription("The actual value of detection time for the session.")
jnxBfdSessIntfName = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 1, 1, 1, 5), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxBfdSessIntfName.setDescription("This object specifies the interface associated with \nthe bfd session")
jnxBfdNotifyObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 2))
jnxBfdSessifName = MibScalar((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 2, 1), DisplayString()).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxBfdSessifName.setDescription("This object gives the Interface Name in the bfdSessUp and \nbfdSessDown trap. Even though this object doesnt appear in \nthe OBJECTS list of these traps, but the agent relay this \ninformation as an extra parameter in the trap.")

# Augmentions

# Notifications

jnxBfdSessTxIntervalHigh = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 0, 1)).setObjects(*(("JUNIPER-BFD-MIB", "jnxBfdSessThreshTxInterval"), ("JUNIPER-BFD-MIB", "jnxBfdSessCurrTxInterval"), ) )
if mibBuilder.loadTexts: jnxBfdSessTxIntervalHigh.setDescription("This notification is generated when the threshold value for \ntransmit interval (jnxBfdSessThreshTxInterval) is set and \nthe bfd session transmit interval (jnxBfdSessCurrTxInterval)\nadapts to a value greater than the threshold value. This trap \nis sent only once, when we first exceed the threshold. The \ntransmit interval can continue  to adapt beyond the threshold \nvalue. Adaptation of transmit interval happens due to network \nissues causing the BFD session to go down on either the local \nsystem or the remote neighbor.")
jnxBfdSessDetectionTimeHigh = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 45, 1, 0, 2)).setObjects(*(("JUNIPER-BFD-MIB", "jnxBfdSessThreshDectTime"), ("JUNIPER-BFD-MIB", "jnxBfdSessCurrDectTime"), ) )
if mibBuilder.loadTexts: jnxBfdSessDetectionTimeHigh.setDescription("This notification is generated when the threshold value for \ndetection time (jnxBfdSessThreshDectTime) is set and the bfd \nsession detection-time (jnxBfdSessCurrDectTime) adapts to a \nvalue greater than the threshold value. This trap is sent only \nonce, when we first exceed the threshold. The detection-time \ncan continue to adapt beyond the threshold value. Adaptation \nof detection-time happens due to network issues causing the \nBFD session to go down on either the local system or the remote \nneighbor.")

# Exports

# Module identity
mibBuilder.exportSymbols("JUNIPER-BFD-MIB", PYSNMP_MODULE_ID=jnxBfdMib)

# Objects
mibBuilder.exportSymbols("JUNIPER-BFD-MIB", jnxBfdMib=jnxBfdMib, jnxBfdNotification=jnxBfdNotification, jnxBfdObjects=jnxBfdObjects, jnxBfdSessTable=jnxBfdSessTable, jnxBfdSessEntry=jnxBfdSessEntry, jnxBfdSessThreshTxInterval=jnxBfdSessThreshTxInterval, jnxBfdSessCurrTxInterval=jnxBfdSessCurrTxInterval, jnxBfdSessThreshDectTime=jnxBfdSessThreshDectTime, jnxBfdSessCurrDectTime=jnxBfdSessCurrDectTime, jnxBfdSessIntfName=jnxBfdSessIntfName, jnxBfdNotifyObjects=jnxBfdNotifyObjects, jnxBfdSessifName=jnxBfdSessifName)

# Notifications
mibBuilder.exportSymbols("JUNIPER-BFD-MIB", jnxBfdSessTxIntervalHigh=jnxBfdSessTxIntervalHigh, jnxBfdSessDetectionTimeHigh=jnxBfdSessDetectionTimeHigh)

