# PySNMP SMI module. Autogenerated from smidump -f python JUNIPER-MOBILE-GATEWAYS
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:57:54 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( InetAddress, InetAddressPrefixLength, InetAddressType, InetPortNumber, ) = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressPrefixLength", "InetAddressType", "InetPortNumber")
( Ipv6Address, Ipv6AddressIfIdentifier, Ipv6AddressPrefix, ) = mibBuilder.importSymbols("IPV6-TC", "Ipv6Address", "Ipv6AddressIfIdentifier", "Ipv6AddressPrefix")
( EnabledStatus, ) = mibBuilder.importSymbols("JUNIPER-MIMSTP-MIB", "EnabledStatus")
( jnxMobileGatewayMibRoot, ) = mibBuilder.importSymbols("JUNIPER-SMI", "jnxMobileGatewayMibRoot")
( Bits, Counter32, Counter64, Integer32, Integer32, IpAddress, ModuleIdentity, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Counter64", "Integer32", "Integer32", "IpAddress", "ModuleIdentity", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32")
( DisplayString, RowStatus, TextualConvention, TruthValue, ) = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "RowStatus", "TextualConvention", "TruthValue")

# Objects

jnxMobileGateways = ModuleIdentity((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4)).setRevisions(("2011-01-03 12:00",))
if mibBuilder.loadTexts: jnxMobileGateways.setOrganization("Juniper Networks, Inc.")
if mibBuilder.loadTexts: jnxMobileGateways.setContactInfo("Juniper Technical Assistance Center\nJuniper Networks, Inc.\n1194 N. Mathilda Avenue\nSunnyvale, CA 94089\nE-mail: support@juniper.net")
if mibBuilder.loadTexts: jnxMobileGateways.setDescription("This module defines objects pertaining to Mobile-Edge Gateways")
jnxMbgGwIndexTable = MibTable((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4, 1))
if mibBuilder.loadTexts: jnxMbgGwIndexTable.setDescription("Each entry corresponds to a mobile gateway ")
jnxMbgGwIndexEntry = MibTableRow((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4, 1, 1)).setIndexNames((0, "JUNIPER-MOBILE-GATEWAYS", "jnxMbgGwIndex"))
if mibBuilder.loadTexts: jnxMbgGwIndexEntry.setDescription("A specification of the mobile gateway")
jnxMbgGwIndex = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4, 1, 1, 1), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxMbgGwIndex.setDescription("Gateway Index.")
jnxMbgGwName = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4, 1, 1, 2), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxMbgGwName.setDescription("Gateway Name.")
jnxMbgGwType = MibTableColumn((1, 3, 6, 1, 4, 1, 2636, 3, 66, 4, 1, 1, 3), DisplayString()).setMaxAccess("readonly")
if mibBuilder.loadTexts: jnxMbgGwType.setDescription("Gateway type: PGW/SGW.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("JUNIPER-MOBILE-GATEWAYS", PYSNMP_MODULE_ID=jnxMobileGateways)

# Objects
mibBuilder.exportSymbols("JUNIPER-MOBILE-GATEWAYS", jnxMobileGateways=jnxMobileGateways, jnxMbgGwIndexTable=jnxMbgGwIndexTable, jnxMbgGwIndexEntry=jnxMbgGwIndexEntry, jnxMbgGwIndex=jnxMbgGwIndex, jnxMbgGwName=jnxMbgGwName, jnxMbgGwType=jnxMbgGwType)

