# PySNMP SMI module. Autogenerated from smidump -f python JUNIPER-MOBILE-GATEWAY-RMPS-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:57:54 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( InetAddress, InetAddressType, InetPortNumber, ) = mibBuilder.importSymbols("INET-ADDRESS-MIB", "InetAddress", "InetAddressType", "InetPortNumber")
( jnxMbgGwName, ) = mibBuilder.importSymbols("JUNIPER-MOBILE-GATEWAYS", "jnxMbgGwName")
( jnxMobileGatewayMibRoot, ) = mibBuilder.importSymbols("JUNIPER-SMI", "jnxMobileGatewayMibRoot")
( Bits, Counter64, Integer32, Integer32, ModuleIdentity, MibIdentifier, NotificationType, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter64", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "NotificationType", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks")
( DisplayString, TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "DisplayString", "TextualConvention")

# Objects

jnxMbgRMPSMib = ModuleIdentity((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7)).setRevisions(("2011-03-23 12:00",))
if mibBuilder.loadTexts: jnxMbgRMPSMib.setOrganization("Juniper Networks, Inc.")
if mibBuilder.loadTexts: jnxMbgRMPSMib.setContactInfo("Juniper Technical Assistance Center\nJuniper Networks, Inc.\n1194 N. Mathilda Avenue\nSunnyvale, CA 94089\nE-mail: support@juniper.net")
if mibBuilder.loadTexts: jnxMbgRMPSMib.setDescription("This module defines objects pertaining to Mobile-Edge Resource Manager")
jnxMbgRMPSNotifications = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 0))
jnxMbgRMPSObjects = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1))
jnxMbgRMPSNotificationVars = MibIdentifier((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1, 5))
jnxMbgRMPSClientIdentifier = MibScalar((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1, 5, 1), DisplayString()).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxMbgRMPSClientIdentifier.setDescription("This identifies the Resource Manager client, in the form \nms-a/b/c or pfe-a/b/c, where <a> is the fpc slot, <b> is pic slot,\nand <c> is the port.")
jnxMbgRMPSClientStatus = MibScalar((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1, 5, 2), Integer().subtype(subtypeSpec=SingleValueConstraint(1,0,)).subtype(namedValues=NamedValues(("inService", 0), ("outOfService", 1), ))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxMbgRMPSClientStatus.setDescription("This specifies the status of a client registered with the Resource\nManager server.")
jnxMbgRMPSServiceStatus = MibScalar((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1, 5, 3), Integer().subtype(subtypeSpec=SingleValueConstraint(1,0,)).subtype(namedValues=NamedValues(("up", 0), ("down", 1), ))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxMbgRMPSServiceStatus.setDescription("This specifies the status of the Resource Manager server.")
jnxMbgRMPSClientRedundancyRole = MibScalar((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 1, 5, 4), Integer().subtype(subtypeSpec=SingleValueConstraint(3,2,1,0,)).subtype(namedValues=NamedValues(("invalid", 0), ("primary", 1), ("secondary", 2), ("standalone", 3), ))).setMaxAccess("notifyonly")
if mibBuilder.loadTexts: jnxMbgRMPSClientRedundancyRole.setDescription("This specifies the redundancy role of the Resource Manager client")

# Augmentions

# Notifications

jnxMbgRMPSServiceStatusChange = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 0, 1)).setObjects(*(("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSServiceStatus"), ) )
if mibBuilder.loadTexts: jnxMbgRMPSServiceStatusChange.setDescription("This notification signifies that status of the Resource Manager\nservice changed.")
jnxMbgRMPSClientStatusChange = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 0, 2)).setObjects(*(("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientStatus"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientIdentifier"), ) )
if mibBuilder.loadTexts: jnxMbgRMPSClientStatusChange.setDescription("This notification signifies that status of a Resource Manager  \nclient changed.")
jnxMbgRMPSClientInfo = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 0, 3)).setObjects(*(("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientRedundancyRole"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientStatus"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientIdentifier"), ) )
if mibBuilder.loadTexts: jnxMbgRMPSClientInfo.setDescription("This notification signifies a change in status or redundancy role\nof the specified Resource Manager client.")
jnxMbgRMPSClientStateChange = NotificationType((1, 3, 6, 1, 4, 1, 2636, 3, 66, 7, 0, 4)).setObjects(*(("JUNIPER-MOBILE-GATEWAYS", "jnxMbgGwName"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientRedundancyRole"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientIdentifier"), ("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", "jnxMbgRMPSClientStatus"), ) )
if mibBuilder.loadTexts: jnxMbgRMPSClientStateChange.setDescription("This notification signifies a change in status or redundancy role\nof the specified Resource Manager client.")

# Exports

# Module identity
mibBuilder.exportSymbols("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", PYSNMP_MODULE_ID=jnxMbgRMPSMib)

# Objects
mibBuilder.exportSymbols("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", jnxMbgRMPSMib=jnxMbgRMPSMib, jnxMbgRMPSNotifications=jnxMbgRMPSNotifications, jnxMbgRMPSObjects=jnxMbgRMPSObjects, jnxMbgRMPSNotificationVars=jnxMbgRMPSNotificationVars, jnxMbgRMPSClientIdentifier=jnxMbgRMPSClientIdentifier, jnxMbgRMPSClientStatus=jnxMbgRMPSClientStatus, jnxMbgRMPSServiceStatus=jnxMbgRMPSServiceStatus, jnxMbgRMPSClientRedundancyRole=jnxMbgRMPSClientRedundancyRole)

# Notifications
mibBuilder.exportSymbols("JUNIPER-MOBILE-GATEWAY-RMPS-MIB", jnxMbgRMPSServiceStatusChange=jnxMbgRMPSServiceStatusChange, jnxMbgRMPSClientStatusChange=jnxMbgRMPSClientStatusChange, jnxMbgRMPSClientInfo=jnxMbgRMPSClientInfo, jnxMbgRMPSClientStateChange=jnxMbgRMPSClientStateChange)

