# PySNMP SMI module. Autogenerated from smidump -f python URI-TC-MIB
# by libsmi2pysnmp-0.1.3 at Thu May 22 11:58:18 2014,
# Python version sys.version_info(major=2, minor=7, micro=2, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( Bits, Integer32, ModuleIdentity, MibIdentifier, TimeTicks, mib_2, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "ModuleIdentity", "MibIdentifier", "TimeTicks", "mib-2")
( TextualConvention, ) = mibBuilder.importSymbols("SNMPv2-TC", "TextualConvention")

# Types

class Uri(TextualConvention, OctetString):
    displayHint = "1a"
    
class Uri1024(TextualConvention, OctetString):
    displayHint = "1024a"
    subtypeSpec = OctetString.subtypeSpec+ValueSizeConstraint(0,1024)
    
class Uri255(TextualConvention, OctetString):
    displayHint = "255a"
    subtypeSpec = OctetString.subtypeSpec+ValueSizeConstraint(0,255)
    

# Objects

uriTcMIB = ModuleIdentity((1, 3, 6, 1, 2, 1, 164)).setRevisions(("2007-09-10 00:00",))
if mibBuilder.loadTexts: uriTcMIB.setOrganization("IETF Operations and Management (OPS) Area")
if mibBuilder.loadTexts: uriTcMIB.setContactInfo("EMail: ops-area@ietf.org\nHome page: http://www.ops.ietf.org/")
if mibBuilder.loadTexts: uriTcMIB.setDescription("This MIB module defines textual conventions for\nrepresenting URIs, as defined by RFC 3986 STD 66.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("URI-TC-MIB", PYSNMP_MODULE_ID=uriTcMIB)

# Types
mibBuilder.exportSymbols("URI-TC-MIB", Uri=Uri, Uri1024=Uri1024, Uri255=Uri255)

# Objects
mibBuilder.exportSymbols("URI-TC-MIB", uriTcMIB=uriTcMIB)

